version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=sekret
      - MYSQL_DATABASE=todos
      - MYSQL_ROOT_PASSWORD=suP#r5ekR3t

  api:
    image: bmansfield/go-mvc-srv:latest
    container_name: go-server
    ports:
      - 8080:8080
    environment:
      - DB_USER=root
      - DB_PASSWORD=suP#r5ekR3t
      - DB_NAME=todos
      - DB_TABLE=tasks
    links:
      - mysql:mysql
